// Generated by app/scripts/make-vision-assets.mjs from the site's atlas-data.js,
// region-notes.js, brodmann-areas.js and mni152.nii.gz. Do not edit.

import simd

/// One entry of the AAL-116 region list as the site shows it: a pair of
/// left and right labels, or a single midline label.
struct AtlasRegion: Hashable {
    let base: String
    let name: String
    let group: String
    let left: Int?
    let right: Int?
    let single: Int?
}

/// What a region does, and which layer of the brain it belongs to.
struct RegionNote {
    let tier: String
    let function: String
}

struct RegionTier: Hashable {
    let id: String
    let label: String
    let sub: String
}

/// One Brodmann area as the shipped atlas draws it, both hemispheres in one label.
struct BrodmannArea: Hashable {
    let ba: Int
    let name: String
    let region: String
    let lobe: String
    let function: String
    let note: String
    let tags: String
}

struct BrodmannLobe: Hashable {
    let id: String
    let label: String
    let sub: String
}

enum AtlasRegions {
    static let all: [AtlasRegion] = [
        AtlasRegion(base: "Precentral", name: "Precentral Gyrus", group: "Frontal", left: 1, right: 2, single: nil),
        AtlasRegion(base: "Frontal_Sup", name: "Superior Frontal Gyrus", group: "Frontal", left: 3, right: 4, single: nil),
        AtlasRegion(base: "Frontal_Sup_Orb", name: "Superior Frontal Gyrus, Orbital", group: "Frontal", left: 5, right: 6, single: nil),
        AtlasRegion(base: "Frontal_Mid", name: "Middle Frontal Gyrus", group: "Frontal", left: 7, right: 8, single: nil),
        AtlasRegion(base: "Frontal_Mid_Orb", name: "Middle Frontal Gyrus, Orbital", group: "Frontal", left: 9, right: 10, single: nil),
        AtlasRegion(base: "Frontal_Inf_Oper", name: "Inferior Frontal Gyrus, Opercular", group: "Frontal", left: 11, right: 12, single: nil),
        AtlasRegion(base: "Frontal_Inf_Tri", name: "Inferior Frontal Gyrus, Triangular", group: "Frontal", left: 13, right: 14, single: nil),
        AtlasRegion(base: "Frontal_Inf_Orb", name: "Inferior Frontal Gyrus, Orbital", group: "Frontal", left: 15, right: 16, single: nil),
        AtlasRegion(base: "Rolandic_Oper", name: "Rolandic Operculum", group: "Frontal", left: 17, right: 18, single: nil),
        AtlasRegion(base: "Supp_Motor_Area", name: "Supplementary Motor Area", group: "Frontal", left: 19, right: 20, single: nil),
        AtlasRegion(base: "Olfactory", name: "Olfactory Cortex", group: "Frontal", left: 21, right: 22, single: nil),
        AtlasRegion(base: "Frontal_Sup_Medial", name: "Superior Frontal Gyrus, Medial", group: "Frontal", left: 23, right: 24, single: nil),
        AtlasRegion(base: "Frontal_Med_Orb", name: "Medial Orbitofrontal Cortex", group: "Frontal", left: 25, right: 26, single: nil),
        AtlasRegion(base: "Rectus", name: "Gyrus Rectus", group: "Frontal", left: 27, right: 28, single: nil),
        AtlasRegion(base: "Insula", name: "Insula", group: "Insula & Cingulate", left: 29, right: 30, single: nil),
        AtlasRegion(base: "Cingulum_Ant", name: "Anterior Cingulate", group: "Insula & Cingulate", left: 31, right: 32, single: nil),
        AtlasRegion(base: "Cingulum_Mid", name: "Middle Cingulate", group: "Insula & Cingulate", left: 33, right: 34, single: nil),
        AtlasRegion(base: "Cingulum_Post", name: "Posterior Cingulate", group: "Insula & Cingulate", left: 35, right: 36, single: nil),
        AtlasRegion(base: "Hippocampus", name: "Hippocampus", group: "Medial Temporal", left: 37, right: 38, single: nil),
        AtlasRegion(base: "ParaHippocampal", name: "Parahippocampal Gyrus", group: "Medial Temporal", left: 39, right: 40, single: nil),
        AtlasRegion(base: "Amygdala", name: "Amygdala", group: "Medial Temporal", left: 41, right: 42, single: nil),
        AtlasRegion(base: "Heschl", name: "Heschl's Gyrus", group: "Temporal", left: 79, right: 80, single: nil),
        AtlasRegion(base: "Temporal_Sup", name: "Superior Temporal Gyrus", group: "Temporal", left: 81, right: 82, single: nil),
        AtlasRegion(base: "Temporal_Pole_Sup", name: "Temporal Pole, Superior", group: "Temporal", left: 83, right: 84, single: nil),
        AtlasRegion(base: "Temporal_Mid", name: "Middle Temporal Gyrus", group: "Temporal", left: 85, right: 86, single: nil),
        AtlasRegion(base: "Temporal_Pole_Mid", name: "Temporal Pole, Middle", group: "Temporal", left: 87, right: 88, single: nil),
        AtlasRegion(base: "Temporal_Inf", name: "Inferior Temporal Gyrus", group: "Temporal", left: 89, right: 90, single: nil),
        AtlasRegion(base: "Postcentral", name: "Postcentral Gyrus", group: "Parietal", left: 57, right: 58, single: nil),
        AtlasRegion(base: "Parietal_Sup", name: "Superior Parietal Lobule", group: "Parietal", left: 59, right: 60, single: nil),
        AtlasRegion(base: "Parietal_Inf", name: "Inferior Parietal Lobule", group: "Parietal", left: 61, right: 62, single: nil),
        AtlasRegion(base: "SupraMarginal", name: "Supramarginal Gyrus", group: "Parietal", left: 63, right: 64, single: nil),
        AtlasRegion(base: "Angular", name: "Angular Gyrus", group: "Parietal", left: 65, right: 66, single: nil),
        AtlasRegion(base: "Precuneus", name: "Precuneus", group: "Parietal", left: 67, right: 68, single: nil),
        AtlasRegion(base: "Paracentral_Lobule", name: "Paracentral Lobule", group: "Parietal", left: 69, right: 70, single: nil),
        AtlasRegion(base: "Calcarine", name: "Calcarine Cortex", group: "Occipital", left: 43, right: 44, single: nil),
        AtlasRegion(base: "Cuneus", name: "Cuneus", group: "Occipital", left: 45, right: 46, single: nil),
        AtlasRegion(base: "Lingual", name: "Lingual Gyrus", group: "Occipital", left: 47, right: 48, single: nil),
        AtlasRegion(base: "Occipital_Sup", name: "Superior Occipital Gyrus", group: "Occipital", left: 49, right: 50, single: nil),
        AtlasRegion(base: "Occipital_Mid", name: "Middle Occipital Gyrus", group: "Occipital", left: 51, right: 52, single: nil),
        AtlasRegion(base: "Occipital_Inf", name: "Inferior Occipital Gyrus", group: "Occipital", left: 53, right: 54, single: nil),
        AtlasRegion(base: "Fusiform", name: "Fusiform Gyrus", group: "Occipital", left: 55, right: 56, single: nil),
        AtlasRegion(base: "Caudate", name: "Caudate Nucleus", group: "Subcortical", left: 71, right: 72, single: nil),
        AtlasRegion(base: "Putamen", name: "Putamen", group: "Subcortical", left: 73, right: 74, single: nil),
        AtlasRegion(base: "Pallidum", name: "Globus Pallidus", group: "Subcortical", left: 75, right: 76, single: nil),
        AtlasRegion(base: "Thalamus", name: "Thalamus", group: "Subcortical", left: 77, right: 78, single: nil),
        AtlasRegion(base: "Cerebelum_Crus1", name: "Cerebellum Crus I", group: "Cerebellum", left: 91, right: 92, single: nil),
        AtlasRegion(base: "Cerebelum_Crus2", name: "Cerebellum Crus II", group: "Cerebellum", left: 93, right: 94, single: nil),
        AtlasRegion(base: "Cerebelum_3", name: "Cerebellum Lobule III", group: "Cerebellum", left: 95, right: 96, single: nil),
        AtlasRegion(base: "Cerebelum_4_5", name: "Cerebellum Lobules IV–V", group: "Cerebellum", left: 97, right: 98, single: nil),
        AtlasRegion(base: "Cerebelum_6", name: "Cerebellum Lobule VI", group: "Cerebellum", left: 99, right: 100, single: nil),
        AtlasRegion(base: "Cerebelum_7b", name: "Cerebellum Lobule VIIb", group: "Cerebellum", left: 101, right: 102, single: nil),
        AtlasRegion(base: "Cerebelum_8", name: "Cerebellum Lobule VIII", group: "Cerebellum", left: 103, right: 104, single: nil),
        AtlasRegion(base: "Cerebelum_9", name: "Cerebellum Lobule IX", group: "Cerebellum", left: 105, right: 106, single: nil),
        AtlasRegion(base: "Cerebelum_10", name: "Cerebellum Lobule X", group: "Cerebellum", left: 107, right: 108, single: nil),
        AtlasRegion(base: "Vermis_1_2", name: "Vermis I–II", group: "Vermis", left: nil, right: nil, single: 109),
        AtlasRegion(base: "Vermis_3", name: "Vermis III", group: "Vermis", left: nil, right: nil, single: 110),
        AtlasRegion(base: "Vermis_4_5", name: "Vermis IV–V", group: "Vermis", left: nil, right: nil, single: 111),
        AtlasRegion(base: "Vermis_6", name: "Vermis VI", group: "Vermis", left: nil, right: nil, single: 112),
        AtlasRegion(base: "Vermis_7", name: "Vermis VII", group: "Vermis", left: nil, right: nil, single: 113),
        AtlasRegion(base: "Vermis_8", name: "Vermis VIII", group: "Vermis", left: nil, right: nil, single: 114),
        AtlasRegion(base: "Vermis_9", name: "Vermis IX", group: "Vermis", left: nil, right: nil, single: 115),
        AtlasRegion(base: "Vermis_10", name: "Vermis X", group: "Vermis", left: nil, right: nil, single: 116),
    ]

    /// The order the site hands colours out in.
    static let palette: [String] = ["#915AD8", "#D85AC9", "#FE4B83", "#FF7847", "#E6C14C", "#AFF05B", "#52F667", "#4AE8B7", "#4FBEE3", "#5575DD"]

    static let tiers: [RegionTier] = [
        RegionTier(id: "cerebrum", label: "Cerebrum", sub: "the neocortical sheet — perception, language, planning, deliberate action"),
        RegionTier(id: "midbrain", label: "Midbrain · limbic", sub: "memory, emotion and the body's inner report"),
        RegionTier(id: "reptilian", label: "Reptilian core", sub: "the deep machinery — relay, habit, balance and timing"),
    ]

    /// Keyed by AAL base name.
    static let notes: [String: RegionNote] = [
        "Precentral": RegionNote(tier: "cerebrum", function: "The primary motor strip. Sends the command that moves the body, mapped along its length from the tongue at the bottom to the foot at the top."),
        "Frontal_Sup": RegionNote(tier: "cerebrum", function: "Superior frontal gyrus. Working memory and the holding of a plan while it is carried out; its medial face belongs to the default network."),
        "Frontal_Sup_Orb": RegionNote(tier: "cerebrum", function: "The orbital surface of the superior frontal gyrus, weighing the value of an option against what else is on offer."),
        "Frontal_Mid": RegionNote(tier: "cerebrum", function: "Middle frontal gyrus, most of the dorsolateral prefrontal cortex. Holds a goal, checks progress against it, and switches when the goal changes."),
        "Frontal_Mid_Orb": RegionNote(tier: "cerebrum", function: "Orbital middle frontal cortex, part of the reward-valuation surface sitting above the eye sockets."),
        "Frontal_Inf_Oper": RegionNote(tier: "cerebrum", function: "Pars opercularis — with pars triangularis this is Broca's area on the left, assembling speech before it is spoken."),
        "Frontal_Inf_Tri": RegionNote(tier: "cerebrum", function: "Pars triangularis. The other half of Broca's area; on the right it does more of the work of inhibiting an action already begun."),
        "Frontal_Inf_Orb": RegionNote(tier: "cerebrum", function: "Orbital inferior frontal cortex, at the junction of language territory and the valuation surface."),
        "Rolandic_Oper": RegionNote(tier: "cerebrum", function: "The operculum folded over the insula, carrying mouth and throat sensation and the motor control of speech."),
        "Supp_Motor_Area": RegionNote(tier: "cerebrum", function: "Supplementary motor area. Prepares and sequences movement — it fires before a self-initiated action, not after it."),
        "Frontal_Sup_Medial": RegionNote(tier: "cerebrum", function: "The medial wall of the superior frontal gyrus. Self-referential thought, and the core of the default network that quiets when a task takes over."),
        "Heschl": RegionNote(tier: "cerebrum", function: "Heschl's gyrus, the primary auditory cortex. First cortical stop for sound, mapped by pitch from one end to the other."),
        "Temporal_Sup": RegionNote(tier: "cerebrum", function: "Superior temporal gyrus. Works sound up into speech; its posterior left portion is Wernicke's territory, where speech becomes meaning."),
        "Temporal_Mid": RegionNote(tier: "cerebrum", function: "Middle temporal gyrus. Association cortex for understood speech and for what things mean, as distinct from how they sound."),
        "Temporal_Inf": RegionNote(tier: "cerebrum", function: "Inferior temporal gyrus, the far end of the ventral visual stream, where seeing becomes recognising."),
        "Postcentral": RegionNote(tier: "cerebrum", function: "The primary somatosensory strip. Receives touch, pressure and limb position, mapped body-part by body-part alongside the motor strip."),
        "Parietal_Sup": RegionNote(tier: "cerebrum", function: "Superior parietal lobule. Holds where things are relative to the body, and keeps that map current as the body moves."),
        "Parietal_Inf": RegionNote(tier: "cerebrum", function: "Inferior parietal lobule. Binds sight, sound and touch into one scene, and supports the sense of a body owning it."),
        "SupraMarginal": RegionNote(tier: "cerebrum", function: "Supramarginal gyrus. Phonological working memory — holding a sound in mind long enough to repeat it — and part of the temporoparietal junction."),
        "Angular": RegionNote(tier: "cerebrum", function: "Angular gyrus. Where written words, numbers and meaning meet; damage on the left disrupts reading and calculation."),
        "Precuneus": RegionNote(tier: "cerebrum", function: "Precuneus. Mental imagery, autobiographical memory and the sense of a self placed in a scene. One of the most metabolically active regions at rest."),
        "Paracentral_Lobule": RegionNote(tier: "cerebrum", function: "The paracentral lobule, over the midline: sensation and motor control for the legs, feet and pelvic floor."),
        "Calcarine": RegionNote(tier: "cerebrum", function: "Calcarine cortex — the primary visual cortex, V1. Every conscious sight starts here, mapped point for point onto the retina."),
        "Cuneus": RegionNote(tier: "cerebrum", function: "Cuneus. Early visual cortex above the calcarine sulcus, handling the lower half of the visual field."),
        "Lingual": RegionNote(tier: "cerebrum", function: "Lingual gyrus. Early visual cortex below the calcarine sulcus, carrying the upper visual field, colour and word form."),
        "Occipital_Sup": RegionNote(tier: "cerebrum", function: "Superior occipital gyrus, an early station on the dorsal stream that tracks where things are and how they move."),
        "Occipital_Mid": RegionNote(tier: "cerebrum", function: "Middle occipital gyrus. Motion and form, and the junction where the dorsal and ventral visual streams part company."),
        "Occipital_Inf": RegionNote(tier: "cerebrum", function: "Inferior occipital gyrus, feeding the ventral stream that turns shapes into recognised objects."),
        "Fusiform": RegionNote(tier: "cerebrum", function: "Fusiform gyrus. Recognises faces, and on the left the visual form of written words."),
        "Olfactory": RegionNote(tier: "midbrain", function: "Olfactory cortex. Smell is the one sense that reaches the cortex without passing through the thalamus first."),
        "Frontal_Med_Orb": RegionNote(tier: "midbrain", function: "Medial orbitofrontal cortex. Puts a value on an outcome, and updates it when the outcome changes."),
        "Rectus": RegionNote(tier: "midbrain", function: "Gyrus rectus, on the underside of the frontal lobe alongside the olfactory tract; part of the ventromedial prefrontal territory tied to social judgement."),
        "Insula": RegionNote(tier: "midbrain", function: "Insula, folded away under the operculum. Reads the state of the body — heartbeat, breath, gut, pain — and turns it into feeling. Its anterior end flags what matters now."),
        "Cingulum_Ant": RegionNote(tier: "midbrain", function: "Anterior cingulate. Registers conflict, effort and error, and prices how much a thing is costing to do."),
        "Cingulum_Mid": RegionNote(tier: "midbrain", function: "Middle cingulate. Links pain and negative outcomes to the actions that would avoid them."),
        "Cingulum_Post": RegionNote(tier: "midbrain", function: "Posterior cingulate. Hub of the default network, and the region whose activity most reliably marks a mind turned inwards."),
        "Hippocampus": RegionNote(tier: "midbrain", function: "Hippocampus. Lays down new episodic memory and maps space; without it, experience stops being recorded."),
        "ParaHippocampal": RegionNote(tier: "midbrain", function: "Parahippocampal gyrus. The corridor into the hippocampus, and where the scene around you is recognised as a place."),
        "Amygdala": RegionNote(tier: "midbrain", function: "Amygdala. Detects threat and emotional significance, and stamps a memory with how much it mattered."),
        "Temporal_Pole_Sup": RegionNote(tier: "midbrain", function: "Superior temporal pole. Paralimbic cortex binding sound and language to emotion and social meaning."),
        "Temporal_Pole_Mid": RegionNote(tier: "midbrain", function: "Middle temporal pole. Semantic memory for people and concepts, and one of the first regions lost in semantic dementia."),
        "Caudate": RegionNote(tier: "reptilian", function: "Caudate nucleus. Learns which action leads to which outcome, and is the striatal end of the loops that start and stop behaviour."),
        "Putamen": RegionNote(tier: "reptilian", function: "Putamen. Turns a practised sequence into a habit that runs without supervision."),
        "Pallidum": RegionNote(tier: "reptilian", function: "Globus pallidus. The basal ganglia's output gate — it holds movement in check, and releases what is selected."),
        "Thalamus": RegionNote(tier: "reptilian", function: "Thalamus. Almost everything the cortex knows arrives through here; it relays and gates, and decides what gets through at all."),
        "Cerebelum_Crus1": RegionNote(tier: "reptilian", function: "Cerebellar Crus I. Connected to prefrontal cortex — this part of the cerebellum works on thought and language, not movement."),
        "Cerebelum_Crus2": RegionNote(tier: "reptilian", function: "Cerebellar Crus II. With Crus I, the cognitive cerebellum, tied to working memory and language."),
        "Cerebelum_3": RegionNote(tier: "reptilian", function: "Cerebellar lobule III. Part of the anterior lobe, working on the limbs and posture."),
        "Cerebelum_4_5": RegionNote(tier: "reptilian", function: "Cerebellar lobules IV–V. The anterior sensorimotor cerebellum, refining the timing and force of movement."),
        "Cerebelum_6": RegionNote(tier: "reptilian", function: "Cerebellar lobule VI. Sensorimotor and cognitive both, and heavily involved in speech."),
        "Cerebelum_7b": RegionNote(tier: "reptilian", function: "Cerebellar lobule VIIb, on the cognitive side of the cerebellum's division of labour."),
        "Cerebelum_8": RegionNote(tier: "reptilian", function: "Cerebellar lobule VIII. A second sensorimotor map, mirroring the anterior lobe's."),
        "Cerebelum_9": RegionNote(tier: "reptilian", function: "Cerebellar lobule IX. Vestibular and default-network connected, tied to balance and to self-motion."),
        "Cerebelum_10": RegionNote(tier: "reptilian", function: "Cerebellar lobule X, the flocculonodular lobe — the oldest part, holding the eyes steady as the head moves."),
        "Vermis_1_2": RegionNote(tier: "reptilian", function: "Vermis I–II, at the top of the midline strip that runs between the two cerebellar hemispheres."),
        "Vermis_3": RegionNote(tier: "reptilian", function: "Vermis III. Midline cerebellum, working on the trunk rather than the limbs."),
        "Vermis_4_5": RegionNote(tier: "reptilian", function: "Vermis IV–V. Posture and the muscles that hold the body upright."),
        "Vermis_6": RegionNote(tier: "reptilian", function: "Vermis VI. Eye movement and the coordination of gaze."),
        "Vermis_7": RegionNote(tier: "reptilian", function: "Vermis VII. Part of the oculomotor vermis, tuning the accuracy of a saccade."),
        "Vermis_8": RegionNote(tier: "reptilian", function: "Vermis VIII. Midline cerebellum for gait and the rhythm of walking."),
        "Vermis_9": RegionNote(tier: "reptilian", function: "Vermis IX. Vestibular midline, tied to balance and to the sense of which way is up."),
        "Vermis_10": RegionNote(tier: "reptilian", function: "Vermis X, the nodulus. Vestibular processing at the cerebellum's oldest core."),
    ]
}

enum Brodmann {
    static let areas: [BrodmannArea] = [
        BrodmannArea(ba: 1, name: "Primary somatosensory cortex", region: "Postcentral gyrus, crown", lobe: "parietal", function: "Touch. Takes the skin senses from the thalamus and lays them out as a map of the body — the homunculus — with the lips and fingertips given far more cortex than their size warrants. Reads texture and the fine detail of contact.", note: "Areas 3, 1 and 2 form one strip and are usually treated together as S1; the boundaries between them are cytoarchitectural, not visible on a scan.", tags: "touch somatosensory S1 skin texture homunculus body map"),
        BrodmannArea(ba: 2, name: "Primary somatosensory cortex", region: "Postcentral gyrus, posterior", lobe: "parietal", function: "Proprioception and shape. The posterior strip of S1, weighted towards deep sensation — joint position, limb pressure, the size and form of a held object rather than the feel of its surface.", note: "Damage here impairs recognising objects by handling them alone, with ordinary touch intact.", tags: "proprioception touch somatosensory S1 shape stereognosis body"),
        BrodmannArea(ba: 3, name: "Primary somatosensory cortex", region: "Posterior bank of the central sulcus", lobe: "parietal", function: "The first cortical stop for body sensation. Area 3b receives skin input and 3a receives muscle spindles, both arriving from the ventral posterior thalamus. Most of it is buried in the sulcus rather than on the surface.", note: "3a and 3b are separate cytoarchitectural fields; this atlas does not divide them.", tags: "touch somatosensory S1 skin proprioception central sulcus"),
        BrodmannArea(ba: 4, name: "Primary motor cortex", region: "Precentral gyrus", lobe: "frontal", function: "Voluntary movement. The output stage: its giant Betz cells contribute much of the corticospinal tract, and stimulating a point here moves a specific part of the body. Mapped as a homunculus mirroring the sensory one across the central sulcus.", note: "It executes rather than decides — the plan arrives from area 6 and the parietal cortex.", tags: "motor M1 movement voluntary movement corticospinal Betz homunculus paralysis"),
        BrodmannArea(ba: 5, name: "Somatosensory association cortex", region: "Superior parietal lobule, anterior", lobe: "parietal", function: "Integrates touch with limb position to build a sense of where the body is and what it is holding. Feeds reaching and grasping.", note: "", tags: "somatosensory association reaching proprioception body superior parietal"),
        BrodmannArea(ba: 6, name: "Premotor cortex and supplementary motor area", region: "Precentral gyrus, anterior; medial frontal", lobe: "frontal", function: "Planning and sequencing movement before it happens. The lateral part prepares movements cued by something in the world; the medial part, the SMA, prepares self-initiated sequences and holds their order.", note: "One Brodmann number covering two functionally distinct territories — lateral premotor and SMA are routinely separated in imaging work.", tags: "premotor supplementary motor area SMA movement planning sequencing preparation"),
        BrodmannArea(ba: 7, name: "Superior parietal lobule and precuneus", region: "Superior parietal, medial and lateral", lobe: "parietal", function: "Where vision meets action: guiding the hand to what the eye has found, holding attention on a location, and building the spatial frame the body moves through. The medial part, the precuneus, is also a hub of the default mode network.", note: "Lesions can produce optic ataxia — reaching that misses under visual guidance while vision and movement are each intact.", tags: "spatial attention reaching visuomotor precuneus default mode optic ataxia eye hand"),
        BrodmannArea(ba: 8, name: "Frontal eye fields and superior frontal", region: "Posterior middle and superior frontal gyri", lobe: "frontal", function: "Moving the eyes on purpose. Contains the frontal eye field, which drives voluntary saccades and holds gaze against distraction; the surrounding cortex is involved in managing uncertainty about what to do next.", note: "The frontal eye field is a part of area 8, not the whole of it.", tags: "frontal eye fields FEF eye movement eye movements saccades gaze looking"),
        BrodmannArea(ba: 9, name: "Dorsolateral prefrontal cortex", region: "Superior and middle frontal gyri", lobe: "frontal", function: "Executive control. Holding information in mind while working on it, sustaining attention, suppressing the obvious-but-wrong response, and keeping a goal in play across a delay.", note: "Areas 9 and 46 together are what most papers mean by DLPFC; the split between them is not consistent across studies.", tags: "dorsolateral prefrontal DLPFC working memory executive function attention control inhibition"),
        BrodmannArea(ba: 10, name: "Frontopolar cortex", region: "Anterior prefrontal, frontal pole", lobe: "frontal", function: "The furthest forward cortex there is, and proportionally larger in humans than in any other primate. Associated with holding an intention while doing something else, switching between goals, and reasoning about things not present.", note: "Among the least understood areas in the brain: it is large, late-developing, and its functions are described more confidently than the evidence supports.", tags: "frontopolar anterior prefrontal prospective memory multitasking planning abstract reasoning"),
        BrodmannArea(ba: 11, name: "Orbitofrontal cortex", region: "Orbital gyri, gyrus rectus", lobe: "frontal", function: "Putting a value on things. Represents how rewarding or aversive an outcome is expected to be, and updates that when the world changes — which is what lets behaviour follow consequences rather than habit.", note: "Damage here spares intelligence and memory while wrecking judgement; Phineas Gage's injury is the classic account.", tags: "orbitofrontal OFC reward value valuation decision making judgement personality"),
        BrodmannArea(ba: 17, name: "Primary visual cortex (V1)", region: "Calcarine sulcus, striate cortex", lobe: "occipital", function: "The first cortical stage of sight. Receives the retina by way of the lateral geniculate nucleus and holds a retinotopic map, with the central few degrees of vision taking a disproportionate share. Its cells respond to edges at particular orientations.", note: "Called striate for the stripe of Gennari visible in section — the one Brodmann area identifiable by eye.", tags: "primary visual V1 striate vision sight seeing retinotopic blindness"),
        BrodmannArea(ba: 18, name: "Secondary visual cortex (V2)", region: "Occipital, surrounding V1", lobe: "occipital", function: "The second pass: binds edges into contours, separates figure from ground, and begins to represent shapes rather than the lines that bound them.", note: "", tags: "V2 secondary visual vision contour figure ground grouping"),
        BrodmannArea(ba: 19, name: "Associative visual cortex (V3, V4, V5)", region: "Lateral and ventral occipital", lobe: "occipital", function: "Where vision divides. Motion, colour constancy and complex form are handled across this territory, and the two great visual streams leave it — dorsally towards the parietal lobe for where and how, ventrally towards the temporal lobe for what.", note: "A Brodmann number covering several functionally distinct visual areas that are now mapped separately.", tags: "V3 V4 V5 MT visual association motion colour color form dorsal ventral stream"),
        BrodmannArea(ba: 20, name: "Inferior temporal gyrus", region: "Inferior temporal, lateral", lobe: "temporal", function: "The far end of the ventral stream: recognising objects regardless of size, lighting or angle. Cells here respond to whole objects rather than to features.", note: "", tags: "inferior temporal object recognition ventral stream vision what pathway"),
        BrodmannArea(ba: 21, name: "Middle temporal gyrus", region: "Middle temporal", lobe: "temporal", function: "Meaning. Involved in retrieving what words and objects refer to, in knowledge of actions and tools, and in making sense of sound that carries information.", note: "Strongly left-lateralised for language in most right-handed people.", tags: "middle temporal semantics language meaning tools actions auditory"),
        BrodmannArea(ba: 22, name: "Superior temporal gyrus, including Wernicke's area", region: "Superior temporal", lobe: "temporal", function: "Turning sound into speech. The posterior part on the left is Wernicke's area, where heard words become words rather than noise; damage produces fluent speech emptied of sense, and comprehension that fails without the speaker noticing.", note: "Wernicke's area is a posterior part of left area 22 — its exact boundary has been disputed for a century.", tags: "Wernicke speech comprehension auditory association language aphasia hearing words"),
        BrodmannArea(ba: 23, name: "Posterior cingulate cortex, ventral", region: "Posterior cingulate", lobe: "cingulate", function: "A core hub of the default mode network: most active when attention is turned inward — remembering, imagining, thinking about oneself — and suppressed by demanding external tasks.", note: "Among the first regions to show reduced metabolism in Alzheimer's disease.", tags: "posterior cingulate PCC default mode self referential memory retrieval Alzheimer"),
        BrodmannArea(ba: 24, name: "Anterior cingulate cortex, ventral", region: "Anterior cingulate", lobe: "cingulate", function: "Where feeling meets control. Registers the affective side of pain and effort, tracks conflict between competing responses, and drives the autonomic changes that go with emotion.", note: "", tags: "anterior cingulate ACC emotion pain autonomic conflict affect"),
        BrodmannArea(ba: 25, name: "Subgenual cingulate cortex", region: "Below the genu of the corpus callosum", lobe: "cingulate", function: "A small area with an outsized role in mood. Overactive in depression and quietened by treatments that work, which made it the target for deep brain stimulation in treatment-resistant cases.", note: "The DBS trials have been mixed: early open-label results were striking, the controlled trial was not.", tags: "subgenual cingulate depression mood deep brain stimulation DBS treatment resistant"),
        BrodmannArea(ba: 26, name: "Ectosplenial area", region: "Behind the splenium, retrosplenial", lobe: "cingulate", function: "A thin strip of retrosplenial cortex involved in spatial memory and in building the scene a remembered or imagined event takes place in.", note: "Small and difficult to separate from areas 29 and 30 on a scan.", tags: "ectosplenial retrosplenial spatial memory scene construction"),
        BrodmannArea(ba: 27, name: "Piriform and presubicular cortex", region: "Medial temporal, uncal", lobe: "temporal", function: "Olfaction, and the approach to the hippocampus. Piriform cortex receives smell directly from the olfactory bulb — the one sense that reaches cortex without passing through the thalamus.", note: "", tags: "piriform olfaction smell presubiculum odour odor"),
        BrodmannArea(ba: 28, name: "Entorhinal cortex", region: "Parahippocampal gyrus, anterior", lobe: "temporal", function: "The doorway to the hippocampus. Nearly everything the cortex sends to memory passes through here, and its grid cells carry a metric for space that underpins navigation.", note: "The first cortical site where Alzheimer's tangles appear, typically years before symptoms.", tags: "entorhinal memory grid cells navigation Alzheimer hippocampus gateway"),
        BrodmannArea(ba: 29, name: "Retrosplenial cingulate, granular", region: "Retrosplenial", lobe: "cingulate", function: "Translating between the view from here and the map from above — the step that lets a remembered layout be used from a new vantage point. Central to navigation and to recalling episodes in their place.", note: "", tags: "retrosplenial navigation spatial orientation episodic memory granular"),
        BrodmannArea(ba: 30, name: "Retrosplenial cingulate, agranular", region: "Retrosplenial", lobe: "cingulate", function: "The agranular half of the retrosplenial cortex, working with area 29 on spatial orientation and episodic memory.", note: "", tags: "retrosplenial navigation spatial orientation episodic memory agranular"),
        BrodmannArea(ba: 32, name: "Anterior cingulate cortex, dorsal", region: "Dorsal anterior cingulate", lobe: "cingulate", function: "Monitoring how things are going: detecting errors, registering conflict between what is being done and what should be, and signalling that more effort is required. A node of the salience network.", note: "Whether it detects conflict, predicts effort cost, or signals surprise is still argued over.", tags: "dorsal anterior cingulate dACC conflict monitoring error detection effort salience"),
        BrodmannArea(ba: 34, name: "Anterior entorhinal cortex", region: "Uncus, medial temporal", lobe: "temporal", function: "The uncal part of the entorhinal region, taking olfactory input and feeding the amygdala and hippocampus.", note: "", tags: "entorhinal uncus olfaction smell amygdala memory"),
        BrodmannArea(ba: 35, name: "Perirhinal cortex", region: "Collateral sulcus, medial temporal", lobe: "temporal", function: "Recognition memory for objects — the sense that a thing has been met before, which is separable from recalling where or when.", note: "", tags: "perirhinal recognition memory familiarity objects"),
        BrodmannArea(ba: 36, name: "Ectorhinal and parahippocampal cortex", region: "Parahippocampal gyrus", lobe: "temporal", function: "Memory for scenes and context. Overlaps the parahippocampal place area, which responds to places and spatial layouts far more than to objects within them.", note: "", tags: "parahippocampal scene context memory place area PPA"),
        BrodmannArea(ba: 37, name: "Fusiform and occipitotemporal cortex", region: "Fusiform gyrus", lobe: "temporal", function: "Recognising the highly practised. Carries the fusiform face area, which responds to faces more than to any other object class, and on the left the visual word form area, which responds to written words in a language the reader knows.", note: "Whether the face area is dedicated to faces or to any category of long expertise is a long-running argument.", tags: "fusiform face recognition faces FFA visual word form reading VWFA colour"),
        BrodmannArea(ba: 38, name: "Temporal pole", region: "Anterior temporal", lobe: "temporal", function: "Where meaning is stored and where meaning meets feeling: general knowledge about things and people, and the emotional weight attached to them.", note: "Atrophies in semantic dementia, which erodes knowledge of what things are while leaving fluent speech.", tags: "temporal pole semantic memory social emotion semantic dementia knowledge"),
        BrodmannArea(ba: 39, name: "Angular gyrus", region: "Inferior parietal lobule, posterior", lobe: "parietal", function: "A crossroads. Involved in reading, in retrieving meaning, in number, and in taking someone else's point of view — functions that share little except needing several kinds of information brought together at once.", note: "Left-sided damage can produce Gerstmann syndrome: losing writing, arithmetic, left-right sense and finger naming together.", tags: "angular gyrus reading semantics number theory of mind Gerstmann arithmetic"),
        BrodmannArea(ba: 40, name: "Supramarginal gyrus", region: "Inferior parietal lobule, anterior", lobe: "parietal", function: "Holding speech sounds in mind long enough to use them, and knowing where the body is and how a tool is handled. The phonological loop of working memory depends on it.", note: "Right-sided damage is a common cause of hemispatial neglect.", tags: "supramarginal phonological loop working memory tool use body schema neglect"),
        BrodmannArea(ba: 41, name: "Primary auditory cortex", region: "Heschl's gyrus", lobe: "temporal", function: "The first cortical stage of hearing, laid out tonotopically — low frequencies at one end, high at the other. Buried in the Sylvian fissure rather than on the surface.", note: "", tags: "primary auditory A1 Heschl hearing sound tonotopic deafness"),
        BrodmannArea(ba: 42, name: "Auditory association cortex", region: "Lateral Heschl's gyrus, planum temporale", lobe: "temporal", function: "The second pass at sound: patterns rather than tones — a melody, a voice, a syllable. Feeds area 22 and the speech system.", note: "The planum temporale is typically larger on the left, one of the earliest anatomical asymmetries found in the human brain.", tags: "auditory association planum temporale hearing sound speech melody voice"),
        BrodmannArea(ba: 43, name: "Subcentral area, gustatory cortex", region: "Base of the pre- and postcentral gyri", lobe: "parietal", function: "Taste, and sensation from the mouth and throat. Sits at the foot of the central sulcus where the body map runs out.", note: "Primary taste cortex is often placed in the frontal operculum and insula as much as here.", tags: "gustatory taste subcentral mouth throat operculum"),
        BrodmannArea(ba: 44, name: "Pars opercularis, Broca's area", region: "Inferior frontal gyrus, posterior", lobe: "frontal", function: "Producing speech and handling its structure. With area 45 it forms Broca's area on the left; damage leaves comprehension largely intact while speech becomes effortful, sparse and stripped of grammar.", note: "Broca's area is areas 44 and 45 on the dominant side — usually but not always the left.", tags: "Broca speech production syntax language aphasia pars opercularis grammar"),
        BrodmannArea(ba: 45, name: "Pars triangularis, Broca's area", region: "Inferior frontal gyrus, anterior", lobe: "frontal", function: "Selecting the right word against competition, and retrieving meaning under control. The more semantic half of Broca's area, where 44 is the more syntactic.", note: "", tags: "Broca semantics word selection language pars triangularis retrieval"),
        BrodmannArea(ba: 46, name: "Dorsolateral prefrontal cortex", region: "Middle frontal gyrus", lobe: "frontal", function: "Keeping information active in the absence of the thing itself, and using it to guide what happens next. The clearest working-memory territory in the frontal lobe.", note: "The standard target for repetitive TMS in depression, usually on the left.", tags: "dorsolateral prefrontal DLPFC working memory attention TMS depression maintenance"),
        BrodmannArea(ba: 47, name: "Pars orbitalis, ventrolateral prefrontal", region: "Inferior frontal gyrus, orbital", lobe: "frontal", function: "Stopping and choosing: suppressing a response already under way, and picking among competing options. Also carries semantic retrieval, continuous with area 45 above it.", note: "", tags: "ventrolateral prefrontal VLPFC inhibition semantics pars orbitalis response selection"),
        BrodmannArea(ba: 48, name: "Peri-Sylvian and insular territory", region: "Insula, operculum, temporal stem", lobe: "temporal", function: "In this atlas, label 48 does not draw Brodmann's retrosubicular area. Cross-tabulated against AAL it is the insula (15%), the Rolandic operculum (10%), the superior temporal gyrus (10%), the putamen (6%) and the supramarginal gyrus (6%), with a third of it falling in white matter that AAL does not label as cortex at all.", note: "Treat this label as the peri-Sylvian territory it actually covers rather than as an area with a function. It is the largest label in the volume — nearly a tenth of everything labelled — which is a sign of a catch-all, not of an area.", tags: "insula insular operculum retrosubicular perisylvian sylvian temporal stem catch all"),
    ]

    static let lobes: [BrodmannLobe] = [
        BrodmannLobe(id: "frontal", label: "Frontal", sub: "movement, planning, speech"),
        BrodmannLobe(id: "parietal", label: "Parietal", sub: "touch, space, the body"),
        BrodmannLobe(id: "temporal", label: "Temporal", sub: "hearing, memory, meaning"),
        BrodmannLobe(id: "occipital", label: "Occipital", sub: "vision"),
        BrodmannLobe(id: "cingulate", label: "Cingulate", sub: "attention, feeling, navigation"),
    ]
}

/// The MNI152 template's millimetre box, which every window centres on.
enum AtlasFrame {
    static let minMm = SIMD3<Float>(-75.7625, -110.7625, -71.7625)
    static let maxMm = SIMD3<Float>(76.1549, 77.2906, 86.0546)
    static var centreMm: SIMD3<Float> { (minMm + maxMm) / 2 }
}
