// Generated by app/scripts/make-vision-assets.mjs from site/assets/atlas-data.js. Do not edit.

/// One entry of the AAL-116 region list as the site shows it: a pair of
/// left and right labels, or a single midline label.
struct AtlasRegion: Hashable {
    let base: String
    let name: String
    let group: String
    let left: Int?
    let right: Int?
    let single: Int?
}

enum AtlasRegions {
    static let all: [AtlasRegion] = [
        AtlasRegion(base: "Precentral", name: "Precentral Gyrus", group: "Frontal", left: 1, right: 2, single: nil),
        AtlasRegion(base: "Frontal_Sup", name: "Superior Frontal Gyrus", group: "Frontal", left: 3, right: 4, single: nil),
        AtlasRegion(base: "Frontal_Sup_Orb", name: "Superior Frontal Gyrus, Orbital", group: "Frontal", left: 5, right: 6, single: nil),
        AtlasRegion(base: "Frontal_Mid", name: "Middle Frontal Gyrus", group: "Frontal", left: 7, right: 8, single: nil),
        AtlasRegion(base: "Frontal_Mid_Orb", name: "Middle Frontal Gyrus, Orbital", group: "Frontal", left: 9, right: 10, single: nil),
        AtlasRegion(base: "Frontal_Inf_Oper", name: "Inferior Frontal Gyrus, Opercular", group: "Frontal", left: 11, right: 12, single: nil),
        AtlasRegion(base: "Frontal_Inf_Tri", name: "Inferior Frontal Gyrus, Triangular", group: "Frontal", left: 13, right: 14, single: nil),
        AtlasRegion(base: "Frontal_Inf_Orb", name: "Inferior Frontal Gyrus, Orbital", group: "Frontal", left: 15, right: 16, single: nil),
        AtlasRegion(base: "Rolandic_Oper", name: "Rolandic Operculum", group: "Frontal", left: 17, right: 18, single: nil),
        AtlasRegion(base: "Supp_Motor_Area", name: "Supplementary Motor Area", group: "Frontal", left: 19, right: 20, single: nil),
        AtlasRegion(base: "Olfactory", name: "Olfactory Cortex", group: "Frontal", left: 21, right: 22, single: nil),
        AtlasRegion(base: "Frontal_Sup_Medial", name: "Superior Frontal Gyrus, Medial", group: "Frontal", left: 23, right: 24, single: nil),
        AtlasRegion(base: "Frontal_Med_Orb", name: "Medial Orbitofrontal Cortex", group: "Frontal", left: 25, right: 26, single: nil),
        AtlasRegion(base: "Rectus", name: "Gyrus Rectus", group: "Frontal", left: 27, right: 28, single: nil),
        AtlasRegion(base: "Insula", name: "Insula", group: "Insula & Cingulate", left: 29, right: 30, single: nil),
        AtlasRegion(base: "Cingulum_Ant", name: "Anterior Cingulate", group: "Insula & Cingulate", left: 31, right: 32, single: nil),
        AtlasRegion(base: "Cingulum_Mid", name: "Middle Cingulate", group: "Insula & Cingulate", left: 33, right: 34, single: nil),
        AtlasRegion(base: "Cingulum_Post", name: "Posterior Cingulate", group: "Insula & Cingulate", left: 35, right: 36, single: nil),
        AtlasRegion(base: "Hippocampus", name: "Hippocampus", group: "Medial Temporal", left: 37, right: 38, single: nil),
        AtlasRegion(base: "ParaHippocampal", name: "Parahippocampal Gyrus", group: "Medial Temporal", left: 39, right: 40, single: nil),
        AtlasRegion(base: "Amygdala", name: "Amygdala", group: "Medial Temporal", left: 41, right: 42, single: nil),
        AtlasRegion(base: "Heschl", name: "Heschl's Gyrus", group: "Temporal", left: 79, right: 80, single: nil),
        AtlasRegion(base: "Temporal_Sup", name: "Superior Temporal Gyrus", group: "Temporal", left: 81, right: 82, single: nil),
        AtlasRegion(base: "Temporal_Pole_Sup", name: "Temporal Pole, Superior", group: "Temporal", left: 83, right: 84, single: nil),
        AtlasRegion(base: "Temporal_Mid", name: "Middle Temporal Gyrus", group: "Temporal", left: 85, right: 86, single: nil),
        AtlasRegion(base: "Temporal_Pole_Mid", name: "Temporal Pole, Middle", group: "Temporal", left: 87, right: 88, single: nil),
        AtlasRegion(base: "Temporal_Inf", name: "Inferior Temporal Gyrus", group: "Temporal", left: 89, right: 90, single: nil),
        AtlasRegion(base: "Postcentral", name: "Postcentral Gyrus", group: "Parietal", left: 57, right: 58, single: nil),
        AtlasRegion(base: "Parietal_Sup", name: "Superior Parietal Lobule", group: "Parietal", left: 59, right: 60, single: nil),
        AtlasRegion(base: "Parietal_Inf", name: "Inferior Parietal Lobule", group: "Parietal", left: 61, right: 62, single: nil),
        AtlasRegion(base: "SupraMarginal", name: "Supramarginal Gyrus", group: "Parietal", left: 63, right: 64, single: nil),
        AtlasRegion(base: "Angular", name: "Angular Gyrus", group: "Parietal", left: 65, right: 66, single: nil),
        AtlasRegion(base: "Precuneus", name: "Precuneus", group: "Parietal", left: 67, right: 68, single: nil),
        AtlasRegion(base: "Paracentral_Lobule", name: "Paracentral Lobule", group: "Parietal", left: 69, right: 70, single: nil),
        AtlasRegion(base: "Calcarine", name: "Calcarine Cortex", group: "Occipital", left: 43, right: 44, single: nil),
        AtlasRegion(base: "Cuneus", name: "Cuneus", group: "Occipital", left: 45, right: 46, single: nil),
        AtlasRegion(base: "Lingual", name: "Lingual Gyrus", group: "Occipital", left: 47, right: 48, single: nil),
        AtlasRegion(base: "Occipital_Sup", name: "Superior Occipital Gyrus", group: "Occipital", left: 49, right: 50, single: nil),
        AtlasRegion(base: "Occipital_Mid", name: "Middle Occipital Gyrus", group: "Occipital", left: 51, right: 52, single: nil),
        AtlasRegion(base: "Occipital_Inf", name: "Inferior Occipital Gyrus", group: "Occipital", left: 53, right: 54, single: nil),
        AtlasRegion(base: "Fusiform", name: "Fusiform Gyrus", group: "Occipital", left: 55, right: 56, single: nil),
        AtlasRegion(base: "Caudate", name: "Caudate Nucleus", group: "Subcortical", left: 71, right: 72, single: nil),
        AtlasRegion(base: "Putamen", name: "Putamen", group: "Subcortical", left: 73, right: 74, single: nil),
        AtlasRegion(base: "Pallidum", name: "Globus Pallidus", group: "Subcortical", left: 75, right: 76, single: nil),
        AtlasRegion(base: "Thalamus", name: "Thalamus", group: "Subcortical", left: 77, right: 78, single: nil),
        AtlasRegion(base: "Cerebelum_Crus1", name: "Cerebellum Crus I", group: "Cerebellum", left: 91, right: 92, single: nil),
        AtlasRegion(base: "Cerebelum_Crus2", name: "Cerebellum Crus II", group: "Cerebellum", left: 93, right: 94, single: nil),
        AtlasRegion(base: "Cerebelum_3", name: "Cerebellum Lobule III", group: "Cerebellum", left: 95, right: 96, single: nil),
        AtlasRegion(base: "Cerebelum_4_5", name: "Cerebellum Lobules IV–V", group: "Cerebellum", left: 97, right: 98, single: nil),
        AtlasRegion(base: "Cerebelum_6", name: "Cerebellum Lobule VI", group: "Cerebellum", left: 99, right: 100, single: nil),
        AtlasRegion(base: "Cerebelum_7b", name: "Cerebellum Lobule VIIb", group: "Cerebellum", left: 101, right: 102, single: nil),
        AtlasRegion(base: "Cerebelum_8", name: "Cerebellum Lobule VIII", group: "Cerebellum", left: 103, right: 104, single: nil),
        AtlasRegion(base: "Cerebelum_9", name: "Cerebellum Lobule IX", group: "Cerebellum", left: 105, right: 106, single: nil),
        AtlasRegion(base: "Cerebelum_10", name: "Cerebellum Lobule X", group: "Cerebellum", left: 107, right: 108, single: nil),
        AtlasRegion(base: "Vermis_1_2", name: "Vermis I–II", group: "Vermis", left: nil, right: nil, single: 109),
        AtlasRegion(base: "Vermis_3", name: "Vermis III", group: "Vermis", left: nil, right: nil, single: 110),
        AtlasRegion(base: "Vermis_4_5", name: "Vermis IV–V", group: "Vermis", left: nil, right: nil, single: 111),
        AtlasRegion(base: "Vermis_6", name: "Vermis VI", group: "Vermis", left: nil, right: nil, single: 112),
        AtlasRegion(base: "Vermis_7", name: "Vermis VII", group: "Vermis", left: nil, right: nil, single: 113),
        AtlasRegion(base: "Vermis_8", name: "Vermis VIII", group: "Vermis", left: nil, right: nil, single: 114),
        AtlasRegion(base: "Vermis_9", name: "Vermis IX", group: "Vermis", left: nil, right: nil, single: 115),
        AtlasRegion(base: "Vermis_10", name: "Vermis X", group: "Vermis", left: nil, right: nil, single: 116),
    ]

    /// The order the site hands colours out in.
    static let palette: [String] = ["#915AD8", "#D85AC9", "#FE4B83", "#FF7847", "#E6C14C", "#AFF05B", "#52F667", "#4AE8B7", "#4FBEE3", "#5575DD"]
}
