/* The Brodmann line map: every area's outline on the face that shows it,
   with a label anchor inside each shape.

   The outlines are the click shapes the Brodmann page has always used,
   traced area by area from the classic scheme; what changed is that the
   raster drawing that once sat beneath them is gone, and the outlines are
   the drawing now. The anchors are computed here as each shape's pole of
   inaccessibility: the interior point farthest from any edge, which is
   where a number reads best in a crescent or a wedge.

   Source of the outlines: the last artwork manifest, read from git history
   so this script keeps working after the raster assets were removed.

     node scripts/make_brodmann_outline.mjs > site/assets/brodmann-outline.js
*/
import { execSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";

const ART_PATH = "site/assets/brodmann-art.js";
const ART_REF  = "970568f:" + ART_PATH;
const src = existsSync(ART_PATH) ? readFileSync(ART_PATH, "utf8")
                                 : execSync("git show " + ART_REF, { encoding: "utf8" });
const w = {}; new Function("window", src)(w);
const ART = w.MN_BA_ART;

/* absolute M/L/C/Z paths, as the tracer wrote them, flattened to rings */
function rings(d){
  const out = []; let cur = null, pt = null;
  const toks = d.match(/[MLCZ]|-?\d*\.?\d+/g);
  let i = 0;
  const num = () => parseFloat(toks[i++]);
  while (i < toks.length){
    const t = toks[i++];
    if (t === "M"){ if (cur && cur.length > 2) out.push(cur); cur = []; pt = [num(), num()]; cur.push(pt); }
    else if (t === "L"){ pt = [num(), num()]; cur.push(pt); }
    else if (t === "C"){
      const p0 = pt, p1 = [num(), num()], p2 = [num(), num()], p3 = [num(), num()];
      for (let k = 1; k <= 8; k++){
        const s = k / 8, u = 1 - s;
        cur.push([u*u*u*p0[0] + 3*u*u*s*p1[0] + 3*u*s*s*p2[0] + s*s*s*p3[0],
                  u*u*u*p0[1] + 3*u*u*s*p1[1] + 3*u*s*s*p2[1] + s*s*s*p3[1]]);
      }
      pt = p3;
    }
    else if (t === "Z"){ if (cur && cur.length > 2) out.push(cur); cur = null; }
  }
  if (cur && cur.length > 2) out.push(cur);
  return out;
}
const area = r => { let a = 0; for (let i = 0, n = r.length; i < n; i++){ const p = r[i], q = r[(i+1)%n]; a += p[0]*q[1] - q[0]*p[1]; } return a / 2; };
function inside(pt, r){
  let c = false;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++){
    const a = r[i], b = r[j];
    if ((a[1] > pt[1]) !== (b[1] > pt[1]) && pt[0] < (b[0]-a[0]) * (pt[1]-a[1]) / (b[1]-a[1]) + a[0]) c = !c;
  }
  return c;
}
function segDist(p, a, b){
  const dx = b[0]-a[0], dy = b[1]-a[1]; const l2 = dx*dx + dy*dy;
  let t = l2 ? ((p[0]-a[0])*dx + (p[1]-a[1])*dy) / l2 : 0; t = Math.max(0, Math.min(1, t));
  const x = a[0] + t*dx - p[0], y = a[1] + t*dy - p[1]; return Math.sqrt(x*x + y*y);
}
function edgeDist(p, rs){
  let m = Infinity;
  for (const r of rs) for (let i = 0, n = r.length; i < n; i++) m = Math.min(m, segDist(p, r[i], r[(i+1)%n]));
  return m;
}
/* pole of inaccessibility by a coarse grid then a fine one around the best */
function pole(rs){
  const outer = rs.reduce((b, r) => Math.abs(area(r)) > Math.abs(area(b)) ? r : b, rs[0]);
  const holes = rs.filter(r => r !== outer && Math.abs(area(r)) < Math.abs(area(outer)));
  const xs = outer.map(p => p[0]), ys = outer.map(p => p[1]);
  const x0 = Math.min(...xs), x1 = Math.max(...xs), y0 = Math.min(...ys), y1 = Math.max(...ys);
  const ok = p => inside(p, outer) && !holes.some(h => inside(p, h));
  let best = null, bestD = -1;
  const search = (ax, ay, bx, by, n) => {
    for (let i = 0; i <= n; i++) for (let j = 0; j <= n; j++){
      const p = [ax + (bx-ax) * i / n, ay + (by-ay) * j / n];
      if (!ok(p)) continue;
      const d = edgeDist(p, rs);
      if (d > bestD){ bestD = d; best = p; }
    }
  };
  search(x0, y0, x1, y1, 40);
  if (best){ const s = Math.max(x1-x0, y1-y0) / 40; search(best[0]-s, best[1]-s, best[0]+s, best[1]+s, 16); }
  return { at: best ? [+best[0].toFixed(1), +best[1].toFixed(1)] : [(x0+x1)/2, (y0+y1)/2], r: +bestD.toFixed(1) };
}

const areas = {};
for (const k of Object.keys(ART.areas)){
  areas[k] = ART.areas[k].map(e => {
    const rs = rings(e.d); const { at, r } = pole(rs);
    return { view: e.view, d: e.d, at, r };
  });
}
const out = { box: ART.box, areas };
process.stdout.write(
`/* The Brodmann line map: each area's outline on the face that shows it,
   and the point inside each shape where its number sits. Generated by
   scripts/make_brodmann_outline.mjs; do not edit by hand. The outlines
   descend from Brodmann's 1909 scheme via the classic redrawn cartoon,
   traced area by area; nothing raster is drawn beneath them. */
window.MN_BA_OUTLINE = ${JSON.stringify(out)};
`);
